import { TenantConfiguration } from "./types";

export function createDefaultTenantConfig(tenantId: string = "BIOAZUCAR-DEMO"): TenantConfiguration {
  return {
    identity: {
      name: "BioAzúcar 4.0 Smart Mill (Site Central)",
      code: tenantId === "BIOAZUCAR-DEMO" ? "BIOAZUCAR-DEMO" : tenantId,
      country: "Venezuela",
      region: "Edo. Portuguesa",
      address: "Carretera Nacional Acarigua - Payara, Km 12",
      timezone: "America/Caracas",
      currency: "USD",
      language: "es",
      contactEmail: "operaciones@bioazucar.com",
      contactPhone: "+58 255 621-4400",
      themeColor: "#10b981",
      description: "Central azucarero inteligente de referencia con simulación de cogeneración, tándem de 5 molinos y caldera de biomasa.",
    },
    caneProcess: {
      nominalTch: 450,
      minTch: 200,
      maxTch: 600,
      millsCount: 5,
      nominalExtraction: 96.5,
      fiberPercent: 13.5,
      nominalBrix: 18.8,
      nominalPol: 15.4,
      nominalPurity: 86.6,
      imbibitionWaterPercent: 28.5,
      recoveryYieldTarget: 11.42,
    },
    bagasse: {
      fiberPercent: 48.2,
      nominalMoisture: 48.8,
      productionFactor: 0.297, // ~134 t/h a 450 TCH
      consumptionFactor: 0.216, // ~97 t/h a caldera
      yardCapacityTons: 65000,
      initialStockTons: 24530,
      lhvKcalPerKg: 1820,
      densityKgM3: 145,
    },
    boilers: {
      count: 1,
      manufacturer: "Babcock & Wilcox Biomasa",
      designPressureBar: 65.0,
      designTempC: 485.0,
      steamCapacityTph: 230.0,
      nominalEfficiency: 85.2,
      targetO2Percent: 3.6,
      flueGasTempC: 168.0,
      blowdownPercent: 2.5,
    },
    turbines: {
      count: 2,
      totalPowerMW: 32.8,
      inletPressureBar: 64.0,
      extractionPressureBar: 2.2,
      exhaustPressureBar: 0.12,
      nominalEfficiency: 82.5,
      speedRpm: 3600,
    },
    grid: {
      installedCapacityMW: 32.8,
      maxExportMW: 24.0,
      gridFrequencyHz: 60.0,
      gridVoltageKV: 138.0,
      targetPowerFactor: 0.94,
      internalConsumptionMW: 11.3,
      ppaTariffUsdPerMWh: 54.5,
    },
    sugar: {
      productType: "Azúcar Blanco Especial & Crudo de Exportación",
      syrupBrixTarget: 66.8,
      sugarYieldPercent: 11.42,
      molassesFactor: 0.035, // tons melaza por ton caña
    },
    tags: {
      "MILL.TANDEM.TCH": {
        tag: "MILL.TANDEM.TCH",
        description: "Molienda horaria de caña (TCH)",
        unit: "t/h",
        dataType: "Double",
        minRange: 0,
        maxRange: 700,
        warningLow: 350,
        warningHigh: 520,
        alarmLow: 250,
        alarmHigh: 580,
        deadband: 2.0,
        samplingIntervalMs: 1000,
        protocol: "SIMULATOR",
      },
      "BOILER.01.PRESSURE": {
        tag: "BOILER.01.PRESSURE",
        description: "Presión vapor alta caldera 1",
        unit: "bar",
        dataType: "Double",
        minRange: 0,
        maxRange: 90,
        warningLow: 58.0,
        warningHigh: 68.0,
        alarmLow: 52.0,
        alarmHigh: 72.0,
        deadband: 0.5,
        samplingIntervalMs: 1000,
        protocol: "SIMULATOR",
      },
      "BOILER.01.STEAM_FLOW": {
        tag: "BOILER.01.STEAM_FLOW",
        description: "Flujo de vapor sobrecalentado HP",
        unit: "t/h",
        dataType: "Double",
        minRange: 0,
        maxRange: 250,
        warningLow: 160,
        warningHigh: 225,
        alarmLow: 120,
        alarmHigh: 235,
        samplingIntervalMs: 1000,
        protocol: "SIMULATOR",
      },
      "TURBINE.01.POWER_MW": {
        tag: "TURBINE.01.POWER_MW",
        description: "Potencia bruta generada turbina",
        unit: "MW",
        dataType: "Double",
        minRange: 0,
        maxRange: 40,
        warningLow: 22,
        warningHigh: 33,
        alarmLow: 15,
        alarmHigh: 35,
        samplingIntervalMs: 1000,
        protocol: "SIMULATOR",
      },
      "GRID.SUBSTATION.EXPORT_MW": {
        tag: "GRID.SUBSTATION.EXPORT_MW",
        description: "Potencia neta exportada al SEN",
        unit: "MW",
        dataType: "Double",
        minRange: 0,
        maxRange: 30,
        warningLow: 12,
        warningHigh: 24,
        alarmLow: 5,
        alarmHigh: 26,
        samplingIntervalMs: 1000,
        protocol: "SIMULATOR",
      },
      "MILL.03.VIBRATION_RMS": {
        tag: "MILL.03.VIBRATION_RMS",
        description: "Vibración chumacera superior Molino 3",
        unit: "mm/s",
        dataType: "Double",
        minRange: 0,
        maxRange: 15,
        warningLow: 0,
        warningHigh: 4.2,
        alarmLow: 0,
        alarmHigh: 4.8,
        samplingIntervalMs: 1000,
        protocol: "SIMULATOR",
      },
      "DIFFUSER.EXTRACTION_EFFICIENCY": {
        tag: "DIFFUSER.EXTRACTION_EFFICIENCY",
        description: "Eficiencia de extracción sacarosa en tándem",
        unit: "%",
        dataType: "Double",
        minRange: 80,
        maxRange: 100,
        warningLow: 94.0,
        warningHigh: 99.0,
        alarmLow: 91.0,
        alarmHigh: 100.0,
        samplingIntervalMs: 1000,
        protocol: "SIMULATOR",
      },
    },
    equipment: [
      {
        id: "eq-molino-3",
        name: "Molino 3 - Extracción Intermedia",
        area: "Molienda",
        criticality: "CRITICA",
        manufacturer: "Fives Cail",
        model: "Heavy Duty 4-Roller 42x84",
        vibrationThresholdMmS: 4.5,
        maintenanceIntervalHours: 720,
      },
      {
        id: "eq-caldera-1",
        name: "Caldera Biomasa 1 (HP 65 bar)",
        area: "Generación de Vapor",
        criticality: "CRITICA",
        manufacturer: "Babcock & Wilcox",
        model: "Biomass Traveling Grate 230 t/h",
        vibrationThresholdMmS: 3.2,
        tempThresholdC: 495,
        maintenanceIntervalHours: 1440,
      },
      {
        id: "eq-turbina-1",
        name: "Turbogenerador Siemens SST-400 (32.8 MW)",
        area: "Cogeneración Eléctrica",
        criticality: "CRITICA",
        manufacturer: "Siemens Energy",
        model: "SST-400 Extraction Condensing",
        vibrationThresholdMmS: 2.8,
        maintenanceIntervalHours: 2160,
      },
      {
        id: "eq-evaporador-cuadruple",
        name: "Evaporador Robert Cuádruple Efecto",
        area: "Fabril / Evaporación",
        criticality: "ALTA",
        manufacturer: "Honiron",
        model: "Robert Falling Film 45,000 sq ft",
        vibrationThresholdMmS: 1.5,
        maintenanceIntervalHours: 1080,
      },
    ],
  };
}
