import {
  IndustrialTagDefinition,
  DataSourceType,
  ProtocolType,
  UserRole,
} from "../types";
import { logAuditEventToDb } from "./dbService";

export const INITIAL_TAG_CATALOG: IndustrialTagDefinition[] = [
  {
    id: "tag-milling-tch",
    name: "Flujo de Molienda TCH",
    description: "Caudal de caña fresca ingresada a báscula y tándem de molienda",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino Picador & Tándem 1",
    variable: "TCH_Actual",
    unit: "TCH",
    dataType: "FLOAT",
    source: "SIMULATION",
    protocol: "SIMULATOR",
    address: "ns=2;s=Milling.Tandem.TCH_Actual",
    accessMode: "READ_WRITE",
    scanRateMs: 1000,
    deadband: 0.5,
    engMin: 0,
    engMax: 600,
    historization: true,
    alarmEnabled: true,
    highAlarm: 480,
    lowAlarm: 380,
    highHighAlarm: 520,
    lowLowAlarm: 320,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-milling-extraction",
    name: "Extracción Sacarosa Tándem",
    description: "Porcentaje de extracción sacarosa en tándem de 6 molinos",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino Picador & Tándem 1",
    variable: "Extraction_Percent",
    unit: "%",
    dataType: "FLOAT",
    source: "SIMULATION",
    protocol: "SIMULATOR",
    address: "ns=2;s=Milling.Tandem.Extraction_Percent",
    accessMode: "READ",
    scanRateMs: 2000,
    deadband: 0.1,
    engMin: 80,
    engMax: 100,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 94.0,
    lowLowAlarm: 91.0,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-mill3-vibration",
    name: "Vibración Molino 3 Chumacera",
    description: "Monitoreo de vibración triaxial en chumacera principal de reducción Molino 3",
    area: "MOLIENDA",
    equipmentId: "eq-molino-3",
    equipmentName: "Molino 03 Corona Principal",
    variable: "Vibration_RMS",
    unit: "mm/s",
    dataType: "FLOAT",
    source: "SIMULATION",
    protocol: "SIMULATOR",
    address: "ns=2;s=Milling.Mill3.VibrationRMS",
    accessMode: "READ",
    scanRateMs: 500,
    deadband: 0.05,
    engMin: 0,
    engMax: 15,
    historization: true,
    alarmEnabled: true,
    highAlarm: 4.5,
    highHighAlarm: 6.0,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-boiler1-steam-press",
    name: "Presión Vapor Alta Presión HP",
    description: "Presión en domo principal Caldera Bagacera Biomasa 1",
    area: "CALDERAS",
    equipmentId: "eq-caldera-1",
    equipmentName: "Caldera Bagacera Biomasa 1",
    variable: "Steam_Pressure_HP",
    unit: "bar",
    dataType: "FLOAT",
    source: "SIMULATION",
    protocol: "SIMULATOR",
    address: "ns=2;s=Boiler1.Drum.Steam_Pressure_HP",
    accessMode: "READ_WRITE",
    scanRateMs: 1000,
    deadband: 0.2,
    engMin: 0,
    engMax: 100,
    historization: true,
    alarmEnabled: true,
    highAlarm: 67.0,
    lowAlarm: 61.0,
    highHighAlarm: 70.0,
    lowLowAlarm: 57.0,
    securityLevel: 3,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-tg1-power-gen",
    name: "Potencia Eléctrica Generada TG1",
    description: "Generación en bornes del turbogenerador de condensación-extracción 1",
    area: "COGENERACION",
    equipmentId: "eq-turbina-1",
    equipmentName: "Turbogenerador TG-01 Siemens 35MW",
    variable: "ActivePower_MW",
    unit: "MW",
    dataType: "FLOAT",
    source: "SIMULATION",
    protocol: "SIMULATOR",
    address: "ns=2;s=Turbine1.Electrical.ActivePower_MW",
    accessMode: "READ",
    scanRateMs: 1000,
    deadband: 0.1,
    engMin: 0,
    engMax: 50,
    historization: true,
    alarmEnabled: true,
    highHighAlarm: 42.0,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-grid-export-mw",
    name: "Potencia Despacho Exportación Red",
    description: "Potencia activa exportada en interruptor de interconexión subestación 138kV",
    area: "COGENERACION",
    equipmentId: "eq-turbina-1",
    equipmentName: "Turbogenerador TG-01 Siemens 35MW",
    variable: "ExportPower_MW",
    unit: "MW",
    dataType: "FLOAT",
    source: "SIMULATION",
    protocol: "SIMULATOR",
    address: "ns=2;s=Grid.Substation.ExportPower_MW",
    accessMode: "READ_WRITE",
    scanRateMs: 1000,
    deadband: 0.1,
    engMin: 0,
    engMax: 40,
    historization: true,
    alarmEnabled: true,
    highAlarm: 26.0,
    lowAlarm: 15.0,
    securityLevel: 3,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-evap-syrup-brix",
    name: "Grados Brix Meladura Evaporadores",
    description: "Concentración en línea del cuerpo 4 de evaporación múltiple efecto",
    area: "EVAPORACION",
    equipmentId: "eq-evaporadores",
    equipmentName: "Estación de Evaporación Cuádruple",
    variable: "Syrup_Brix",
    unit: "°Bx",
    dataType: "FLOAT",
    source: "SIMULATION",
    protocol: "SIMULATOR",
    address: "ns=2;s=Evaporator.Body4.Syrup_Brix",
    accessMode: "READ",
    scanRateMs: 2000,
    deadband: 0.2,
    engMin: 40,
    engMax: 85,
    historization: true,
    alarmEnabled: true,
    highAlarm: 70.0,
    lowAlarm: 62.0,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  // --- TÁNDEM #1 FAT/SAT COMMISSIONING TAGS (25 TAGS SUITE) ---
  {
    id: "tag-prep-desfib-rpm",
    name: "Velocidad Desfibrador Caña",
    description: "Sensor tacométrico inductivo en rotor de desfibramiento pesado",
    area: "MOLIENDA",
    equipmentId: "eq-desfibrador-1",
    equipmentName: "Desfibrador de Caña Tándem 1",
    variable: "DESFIBRADOR_RPM",
    unit: "RPM",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=Prep.Desfib.Speed",
    accessMode: "READ",
    scanRateMs: 500,
    deadband: 1.0,
    engMin: 0,
    engMax: 1500,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 1100,
    highAlarm: 1450,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-prep-open-cell",
    name: "Índice de Celdas Abiertas (IOC)",
    description: "Analizador NIR en línea grado de preparación caña desfibrada",
    area: "MOLIENDA",
    equipmentId: "eq-desfibrador-1",
    equipmentName: "Desfibrador de Caña Tándem 1",
    variable: "OPEN_CELL_PCT",
    unit: "%",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40024",
    accessMode: "READ",
    scanRateMs: 5000,
    deadband: 0.2,
    engMin: 70,
    engMax: 95,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 84.0,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m1-speed-rpm",
    name: "Velocidad Molino 1 (Maza Superior)",
    description: "Variador de frecuencia VFD de accionamiento motor principal M1",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino 01 Tándem",
    variable: "SPEED_RPM",
    unit: "RPM",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=M1.Drive.Speed",
    accessMode: "READ_WRITE",
    scanRateMs: 500,
    deadband: 0.05,
    engMin: 0,
    engMax: 6.5,
    historization: true,
    alarmEnabled: true,
    highAlarm: 5.8,
    securityLevel: 3,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m1-hyd-press",
    name: "Presión Hidráulica Molino 1",
    description: "Presión de acumuladores oleohidráulicos chumacera maza superior M1",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino 01 Tándem",
    variable: "HYDRAULIC_PRESS_BAR",
    unit: "bar",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=M1.Hyd.Press",
    accessMode: "READ",
    scanRateMs: 200,
    deadband: 0.5,
    engMin: 0,
    engMax: 350,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 240,
    highAlarm: 320,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m1-torque-knm",
    name: "Torque Accionamiento Molino 1",
    description: "Célula extensométrica de torsión dinámica en eje motriz Molino 1",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino 01 Tándem",
    variable: "TORQUE_KNM",
    unit: "kNm",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=M1.Drive.Torque",
    accessMode: "READ",
    scanRateMs: 200,
    deadband: 1.0,
    engMin: 0,
    engMax: 1200,
    historization: true,
    alarmEnabled: true,
    highAlarm: 1050,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m1-temp-nde",
    name: "Temperatura Chumacera NDE M1",
    description: "Termorresistencia PT100 3 hilos en chumacera lado no acople M1",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino 01 Tándem",
    variable: "BEARING_NDE_TEMP_C",
    unit: "°C",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40050",
    accessMode: "READ",
    scanRateMs: 1000,
    deadband: 0.5,
    engMin: 0,
    engMax: 150,
    historization: true,
    alarmEnabled: true,
    highAlarm: 70,
    highHighAlarm: 85,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m2-hyd-press",
    name: "Presión Hidráulica Molino 2",
    description: "Transmisor piezorresistivo de presión en cabezal hidráulico Molino 2",
    area: "MOLIENDA",
    equipmentId: "eq-molino-2",
    equipmentName: "Molino 02 Tándem",
    variable: "HYDRAULIC_PRESS_BAR",
    unit: "bar",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=M2.Hyd.Press",
    accessMode: "READ",
    scanRateMs: 200,
    deadband: 0.5,
    engMin: 0,
    engMax: 350,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 250,
    highAlarm: 320,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m3-hyd-press",
    name: "Presión Hidráulica Molino 3",
    description: "Transmisor de presión hidráulica en acumulador maza superior Molino 3",
    area: "MOLIENDA",
    equipmentId: "eq-molino-3",
    equipmentName: "Molino 03 Corona Principal",
    variable: "HYDRAULIC_PRESS_BAR",
    unit: "bar",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=M3.Hyd.Press",
    accessMode: "READ",
    scanRateMs: 200,
    deadband: 0.5,
    engMin: 0,
    engMax: 350,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 260,
    highAlarm: 330,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m4-hyd-press",
    name: "Presión Hidráulica Molino 4",
    description: "Transmisor de presión hidráulica en maza superior Molino 4",
    area: "MOLIENDA",
    equipmentId: "eq-molino-4",
    equipmentName: "Molino 04 Tándem",
    variable: "HYDRAULIC_PRESS_BAR",
    unit: "bar",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=M4.Hyd.Press",
    accessMode: "READ",
    scanRateMs: 200,
    deadband: 0.5,
    engMin: 0,
    engMax: 350,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 260,
    highAlarm: 335,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-m5-hyd-press",
    name: "Presión Hidráulica Molino 5 (Salida)",
    description: "Transmisor de presión en molino de agotamiento final bagazo M5",
    area: "MOLIENDA",
    equipmentId: "eq-molino-5",
    equipmentName: "Molino 05 Salida Bagazo",
    variable: "HYDRAULIC_PRESS_BAR",
    unit: "bar",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=M5.Hyd.Press",
    accessMode: "READ",
    scanRateMs: 200,
    deadband: 0.5,
    engMin: 0,
    engMax: 350,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 270,
    highAlarm: 340,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-imb-flow",
    name: "Caudal Agua de Imbibición Compuesta",
    description: "Medidor electromagnético de caudal de agua caliente a Molino 4 y 5",
    area: "MOLIENDA",
    equipmentId: "eq-imbibicion",
    equipmentName: "Sistema de Imbibición Compuesta",
    variable: "WATER_FLOW_M3H",
    unit: "m³/h",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=Imb.Flow",
    accessMode: "READ_WRITE",
    scanRateMs: 500,
    deadband: 0.2,
    engMin: 0,
    engMax: 200,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 70,
    highAlarm: 150,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-imb-temp",
    name: "Temperatura Agua de Imbibición",
    description: "Termopar tipo K con transmisor en línea de alimentación de imbibición",
    area: "MOLIENDA",
    equipmentId: "eq-imbibicion",
    equipmentName: "Sistema de Imbibición Compuesta",
    variable: "WATER_TEMP_C",
    unit: "°C",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40082",
    accessMode: "READ",
    scanRateMs: 1000,
    deadband: 0.5,
    engMin: 0,
    engMax: 100,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 60,
    highAlarm: 85,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-juice-flow",
    name: "Caudal Jugo Mixto a Báscula",
    description: "Flujómetro electromagnético de jugo mixto bombeado hacia alcalización",
    area: "MOLIENDA",
    equipmentId: "eq-jugo-mixto",
    equipmentName: "Báscula y Bombeo Jugo Mixto",
    variable: "MIXED_JUICE_FLOW_M3H",
    unit: "m³/h",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=Juice.Flow",
    accessMode: "READ",
    scanRateMs: 500,
    deadband: 0.5,
    engMin: 0,
    engMax: 600,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 200,
    highAlarm: 520,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-juice-brix",
    name: "Grados Brix Jugo Mixto",
    description: "Refractómetro óptico industrial en línea en tubería de descarga de jugo",
    area: "MOLIENDA",
    equipmentId: "eq-jugo-mixto",
    equipmentName: "Báscula y Bombeo Jugo Mixto",
    variable: "MIXED_JUICE_BRIX",
    unit: "°Bx",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40090",
    accessMode: "READ",
    scanRateMs: 2000,
    deadband: 0.05,
    engMin: 10,
    engMax: 24,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 13.0,
    highAlarm: 18.5,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-juice-pol",
    name: "Porcentaje Pol en Jugo Mixto",
    description: "Sacarímetro automático polarímetro digital de flujo continuo",
    area: "MOLIENDA",
    equipmentId: "eq-jugo-mixto",
    equipmentName: "Báscula y Bombeo Jugo Mixto",
    variable: "MIXED_JUICE_POL",
    unit: "%",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40092",
    accessMode: "READ",
    scanRateMs: 5000,
    deadband: 0.05,
    engMin: 8,
    engMax: 20,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 11.5,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-juice-ph",
    name: "pH de Jugo Mixto Primario",
    description: "Electrodo combinado de pH de proceso con autolimpieza ultrasónica",
    area: "MOLIENDA",
    equipmentId: "eq-jugo-mixto",
    equipmentName: "Báscula y Bombeo Jugo Mixto",
    variable: "MIXED_JUICE_PH",
    unit: "pH",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40096",
    accessMode: "READ",
    scanRateMs: 1000,
    deadband: 0.02,
    engMin: 3.0,
    engMax: 9.0,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 5.0,
    highAlarm: 5.8,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-bagasse-moisture",
    name: "Humedad Bagazo Final Salida M5",
    description: "Sensor industrial de microondas de medición continua en faja transportadora",
    area: "MOLIENDA",
    equipmentId: "eq-bagazo-salida",
    equipmentName: "Faja Transportadora de Bagazo",
    variable: "BAGASSE_MOISTURE",
    unit: "%",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40102",
    accessMode: "READ",
    scanRateMs: 2000,
    deadband: 0.3,
    engMin: 40,
    engMax: 60,
    historization: true,
    alarmEnabled: true,
    highAlarm: 51.5,
    highHighAlarm: 54.0,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-chute-donnelly-level",
    name: "Nivel Chute Donnelly Molino 1",
    description: "Sensor radar onda guiada en conducto de caída forzada caña desmenuzada",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino 01 Tándem",
    variable: "CHUTE_LEVEL_DONNELLY",
    unit: "%",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "OPC-UA",
    address: "ns=2;s=Chute.Level",
    accessMode: "READ",
    scanRateMs: 200,
    deadband: 1.0,
    engMin: 0,
    engMax: 100,
    historization: true,
    alarmEnabled: true,
    lowAlarm: 30,
    highAlarm: 90,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tag-drive-total-power-kw",
    name: "Potencia Total Accionamientos Tándem",
    description: "Multímetro de red analizador de armónicos en tablero central de fuerza",
    area: "MOLIENDA",
    equipmentId: "eq-molino-1",
    equipmentName: "Molino Picador & Tándem 1",
    variable: "TOTAL_POWER_KW",
    unit: "kW",
    dataType: "FLOAT",
    source: "LIVE_OT",
    protocol: "MODBUS-TCP",
    address: "HOLDING_REGISTER:40120",
    accessMode: "READ",
    scanRateMs: 500,
    deadband: 5.0,
    engMin: 0,
    engMax: 6000,
    historization: true,
    alarmEnabled: true,
    highAlarm: 5200,
    securityLevel: 2,
    status: "ACTIVE",
    tenantId: "TENANT_AZUCAR_01",
    createdAt: new Date().toISOString(),
  },
];

export class TagManagementService {
  private static instance: TagManagementService;
  private memoryTags: Map<string, IndustrialTagDefinition> = new Map();

  private constructor() {
    INITIAL_TAG_CATALOG.forEach((t) => this.memoryTags.set(t.id, t));
  }

  public static getInstance(): TagManagementService {
    if (!TagManagementService.instance) {
      TagManagementService.instance = new TagManagementService();
    }
    return TagManagementService.instance;
  }

  public async getTags(tenantId?: string): Promise<IndustrialTagDefinition[]> {
    const all = Array.from(this.memoryTags.values());
    if (!tenantId || tenantId === "GLOBAL" || tenantId === "ALL") {
      return all;
    }
    return all.filter((t) => !t.tenantId || t.tenantId === tenantId);
  }

  public async getTagById(tagId: string): Promise<IndustrialTagDefinition | null> {
    return this.memoryTags.get(tagId) || null;
  }

  public async createTag(
    tag: Omit<IndustrialTagDefinition, "id" | "createdAt">,
    user: { role: UserRole; name: string }
  ): Promise<IndustrialTagDefinition> {
    const id = `tag-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`;
    const newTag: IndustrialTagDefinition = {
      ...tag,
      id,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    this.memoryTags.set(id, newTag);

    await logAuditEventToDb({
      timestamp: new Date().toISOString(),
      userRole: user.role,
      userName: user.name,
      action: "CREATE_TAG",
      module: "TAG_MANAGEMENT",
      targetId: id,
      newValue: JSON.stringify({ name: newTag.name, address: newTag.address, source: newTag.source }),
      status: "EXECUTED",
      ipAddress: "127.0.0.1",
      tenantId: newTag.tenantId,
    });

    return newTag;
  }

  public async updateTag(
    tagId: string,
    updates: Partial<IndustrialTagDefinition>,
    user: { role: UserRole; name: string }
  ): Promise<IndustrialTagDefinition | null> {
    const existing = this.memoryTags.get(tagId);
    if (!existing) return null;

    const updated: IndustrialTagDefinition = {
      ...existing,
      ...updates,
      updatedAt: new Date().toISOString(),
    };

    this.memoryTags.set(tagId, updated);

    await logAuditEventToDb({
      timestamp: new Date().toISOString(),
      userRole: user.role,
      userName: user.name,
      action: "UPDATE_TAG_CONFIG",
      module: "TAG_MANAGEMENT",
      targetId: tagId,
      previousValue: JSON.stringify({ name: existing.name, address: existing.address }),
      newValue: JSON.stringify(updates),
      status: "EXECUTED",
      ipAddress: "127.0.0.1",
      tenantId: updated.tenantId,
    });

    return updated;
  }

  public async deleteTag(
    tagId: string,
    user: { role: UserRole; name: string }
  ): Promise<boolean> {
    const existing = this.memoryTags.get(tagId);
    if (!existing) return false;

    this.memoryTags.delete(tagId);

    await logAuditEventToDb({
      timestamp: new Date().toISOString(),
      userRole: user.role,
      userName: user.name,
      action: "DELETE_TAG",
      module: "TAG_MANAGEMENT",
      targetId: tagId,
      previousValue: JSON.stringify({ name: existing.name, address: existing.address }),
      status: "EXECUTED",
      ipAddress: "127.0.0.1",
      tenantId: existing.tenantId,
    });

    return true;
  }
}

export const tagManagementService = TagManagementService.getInstance();
