import { NavigationTab, UserRole, DataSourceType, ProtocolType, DataQuality } from "../../types";

// ============================================================================
// BIOAZÚCAR COPILOT — KNOWLEDGE & CONTEXT ENGINE DOMAIN TYPES
// ============================================================================

export type ExplanationStyle = "SIMPLE" | "TECHNICAL" | "AUTOMATION" | "LIVE_GROUNDED";

export type EvidenceCategory =
  | "DOCUMENTATION"
  | "LIVE_DATA"
  | "HISTORICAL_DATA"
  | "INFERENCE"
  | "SIMULATION"
  | "PRODUCTION_OT";

export type ModuleImplementationStatus =
  | "IMPLEMENTED"
  | "PARTIAL"
  | "PLANNED"
  | "NOT_IMPLEMENTED";

/**
 * Entry for the Industrial and Functional Glossary
 */
export interface IndustrialGlossaryEntry {
  id: string;
  name: string;
  term: string;
  aliases: string[];
  definition: string;
  simpleExplanation: string;
  technicalExplanation: string;
  automationExplanation: string;
  bioAzucarExample: string;
  module: NavigationTab;
  category:
    | "OT_HARDWARE"
    | "COMMUNICATION_PROTOCOL"
    | "SOFTWARE_ARCHITECTURE"
    | "SUGAR_PROCESS"
    | "ENERGY_COGENERATION"
    | "MAINTENANCE_CBM"
    | "QUALITY_LIMS"
    | "INDUSTRIAL_STANDARD"
    | "SECURITY_RBAC"
    | "DATA_GOVERNANCE";
  relatedEntities?: string[];
  relatedTagsOrKpis?: string[];
  standards?: string[];
}

/**
 * Structured documentation for each application module
 */
export interface ModuleDocumentation {
  id: NavigationTab;
  name: string;
  purpose: string;
  targetUsers: UserRole[];
  requiredPermissions: string[];
  securityLevelRequired: number;
  implementationStatus: ModuleImplementationStatus;
  features: string[];
  dataDisplayed: string[];
  kpis: string[];
  availableActions: Array<{
    id: string;
    label: string;
    description: string;
    requiredPermission: string;
    level: number;
  }>;
  relatedNavigation: NavigationTab[];
  keyConcepts: string[];
  dataSources: DataSourceType[];
  limitations: string[];
  frequentProcedures: Array<{
    id: string;
    title: string;
    steps: string[];
    requiredRole: UserRole;
    safetyWarning?: string;
  }>;
}

/**
 * Operational SOP procedure
 */
export interface OperationalProcedure {
  id: string;
  title: string;
  category: "OPERATION" | "MAINTENANCE" | "SAFETY" | "CONFIGURATION" | "QUALITY";
  targetModule: NavigationTab;
  requiredRole: UserRole;
  securityLevel: number;
  description: string;
  safetyPreconditions: string[];
  steps: string[];
  evidenceValidation: string;
  relatedEquipment?: string[];
  relatedTags?: string[];
  standards?: string[];
}

/**
 * Knowledge Graph Node
 */
export interface KnowledgeGraphNode {
  id: string;
  type:
    | "TENANT"
    | "SITE"
    | "AREA"
    | "PROCESS"
    | "EQUIPMENT"
    | "TAG"
    | "ALARM"
    | "KPI"
    | "DATA_SOURCE"
    | "PROTOCOL"
    | "DOCUMENTATION"
    | "PROCEDURE";
  name: string;
  code?: string;
  category?: string;
  metadata?: Record<string, any>;
}

/**
 * Knowledge Graph Edge
 */
export interface KnowledgeGraphEdge {
  source: string;
  target: string;
  relation:
    | "CONTAINS"
    | "FEEDS"
    | "MONITORS"
    | "TRIGGERS"
    | "CALCULATES"
    | "USES_PROTOCOL"
    | "GOVERNS"
    | "DOCUMENTS"
    | "RESOLVES"
    | "LOCATED_IN";
  description?: string;
}

/**
 * Tutorial / Walkthrough Step
 */
export interface TutorialStep {
  stepNumber: number;
  totalSteps: number;
  module: NavigationTab;
  title: string;
  roleAudience: UserRole[];
  objective: string;
  explanation: string;
  whatToObserve: string[];
  suggestedAction: {
    label: string;
    actionType: "NAVIGATE" | "RUN_TOOL" | "NEXT_STEP";
    targetTab?: NavigationTab;
  };
}

/**
 * Contextual Evidence Bundle generated by RAG
 */
export interface KnowledgeEvidenceBundle {
  query: string;
  activeModule: NavigationTab;
  glossaryHits: IndustrialGlossaryEntry[];
  moduleDoc?: ModuleDocumentation;
  procedures: OperationalProcedure[];
  graphRelations: {
    nodes: KnowledgeGraphNode[];
    edges: KnowledgeGraphEdge[];
  };
  liveDataProvenance: Array<{
    tag: string;
    value: any;
    unit: string;
    quality: DataQuality;
    source: DataSourceType;
    isSimulated: boolean;
    timestamp: string;
  }>;
  evidenceCategory: EvidenceCategory;
  explanationStyle: ExplanationStyle;
  disclaimer?: string;
}
